apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240222211832.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240222211832.0.0+build.6aff574
  releaseNotes: |
    Release v20240222211832.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-22-02-2024-10-46-47-374910470/where-for-dinner-my-apps-bundle@sha256:86e84730591e9968b22f045ce533ea780be91cc977ef64204456df3c38c4c7fe
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

